name: Send Release Notify Telegram
on:
  release:
    types: [published]
jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: -1002080383068
        RELEASE_TAG: ${{ github.event.release.tag_name }}
        RELEASE_URL: ${{ github.event.release.html_url }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d text="A new release is available: ${RELEASE_TAG}. Check it out at ${RELEASE_URL}"
